### ISSUE TITLE
invalid secret key when injecting service in startup

### ISSUE THREAD

**Issue by GMurtazaShaikh** [checkout/checkout-sdk-net#178]
Trying Checkout SDK in startup as dependency injection using Four API gives "invalid secret key" error but works fine when using  directly.

### Environment

* Checkout SDK version: 3.7.0
* Platform and version:  Visual studio for Mac Community 8.10.19
* Operating System and version: MacOs Monterey 12.2.1

### Description
Trying Checkout SDK in startup as dependency injection using Four API gives "invalid secret key" error but works fine when using  directly I am using follwing code:
CheckoutServiceCollection.AddCheckoutSdk( services, _configuration ); // this gives error of invalid key
 and in appsettings.josn I have
 "Checkout": {
        "SecretKey": "secret key",
        "PublicKey": "public key",
        "Environment": "Sandbox",
        "PlatformType": "Default",
        "FilesEnvironment": "Sandbox"
    }

### Expected behavior
It should inject the service and works as expected so that I can use api injecting in class

### Current behavior
invalid secret key, exception thrown

### Possible solution

- [ ] I may be able to implement this bug fix

**Comment by rsaestrela** [comment]
Hi @GMurtazaShaikh. Thanks for creating this issue.

I found out that the problem is that you specified `Default` instead of `Four` in the platform type attribute. There are 3 possible values for platform type depending on the type of your keys: `Default`, `Four` and `FourOAuth`.

In your case changing the PlatformType to `Four` should solve the issue.
```
"Checkout": {
   "SecretKey": "secret key",
   "PublicKey": "public key",
   "Environment": "Sandbox",
   "PlatformType": "Four",
}
```
We're sorry this detail is not explained in the project README.md - we're going to rework it to make more clear on how to setup these properties. Let me know if it worked for you, we'd be happy to help you if you need something else.

**Comment by GMurtazaShaikh** [comment]
Hi @rsaestrela , Thanks for clarification, It's now working with changes you suggested. and yes detailed documentation would help more. by the way thanks for quick response.
